import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React, { lazy, Suspense } from 'react';
const inter = Inter({ subsets: ['latin'] })
const Navbar = React.lazy(() => import('@/components/main/Navbar'));

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<p>Loading...</p>}>
          <Navbar />
        </Suspense>
        {children}</body>
    </html>
  )
}
